// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.16;

import {IUniswapV2Router01} from "../../../utils/interfaces/IUniswapV2Router01.sol";
import {IERC20} from "../../../utils/interfaces/IERC20.sol";

/// @dev This contract has a constructor that is at the
///      limit of the allowed compilation time stack size
contract AbsurdDeclaration {
    address public storage1;
    address public storage2;
    address public storage3;
    address public storage4;
    address public storage5;
    address public storage6;
    address public storage7;
    address public storage8;
    address public storage9;
    address public storage10;
    address public storage11;
    address public storage12;
    address public storage13;
    address public storage14;
    address public storage15;
    address public storage16;
    address public storage17;
    address public storage18;
    address public storage19;
    address public storage20;
    address public storage21;
    address public storage22;
    address public storage23;
    address public storage24;
    address public storage25;
    address public storage26;
    address public storage27;
    address public storage28;
    address public storage29;
    address public storage30;
    address public storage31;
    address public storage32;
    address public storage33;
    address public storage34;
    address public storage35;
    address public storage36;
    address public storage37;
    address public storage38;
    address public storage39;
    address public storage40;
    address public storage41;
    address public storage42;
    address public storage43;
    address public storage44;
    address public storage45;
    address public storage46;
    address public storage47;
    address public storage48;
    address public storage49;
    address public storage50;
    address public storage51;
    address public storage52;
    address public storage53;
    address public storage54;
    address public storage55;
    address public storage56;
    address public storage57;
    address public storage58;
    address public storage59;
    address public storage60;
    address public storage61;
    address public storage62;
    address public storage63;
    address public storage64;
    address public storage65;
    address public storage66;
    address public storage67;
    address public storage68;

    constructor() {
        storage1 = address(1);
        storage2 = address(2);
        storage3 = address(3);
        storage4 = address(4);
        storage5 = address(5);
        storage6 = address(6);
        storage7 = address(7);
        storage8 = address(8);
        storage9 = address(9);
        storage10 = address(10);
        storage11 = address(11);
        storage12 = address(12);
        storage13 = address(3);
        storage14 = address(14);
        storage15 = address(15);
        storage16 = address(16);
        storage17 = address(7);
        storage18 = address(18);
        storage19 = address(19);
        storage20 = address(20);
        storage21 = address(1);
        storage22 = address(22);
        storage23 = address(23);
        storage24 = address(24);
        storage25 = address(5);
        storage26 = address(26);
        storage27 = address(27);
        storage28 = address(28);
        storage29 = address(9);
        storage30 = address(30);
        storage31 = address(31);
        storage32 = address(32);
        storage33 = address(3);
        storage34 = address(34);
        storage35 = address(35);
        storage36 = address(36);
        storage37 = address(7);
        storage38 = address(38);
        storage39 = address(39);
        storage40 = address(40);
        storage41 = address(1);
        storage42 = address(42);
        storage43 = address(43);
        storage44 = address(44);
        storage45 = address(5);
        storage46 = address(46);
        storage47 = address(47);
        storage48 = address(48);
        storage49 = address(9);
        storage50 = address(50);
        storage51 = address(51);
        storage52 = address(52);
        storage53 = address(3);
        storage54 = address(54);
        storage55 = address(55);
        storage56 = address(56);
        storage57 = address(7);
        storage58 = address(58);
        storage59 = address(59);
        storage60 = address(60);
        storage61 = address(1);
        storage62 = address(62);
        storage63 = address(63);
        storage64 = address(64);
        storage65 = address(5);
        storage66 = address(66);
        storage67 = address(67);
        storage68 = address(68);

        // 16 x 0x14 value on the stack. One more and this file can't be compiled
        address stack1 = storage1;
        address stack2 = storage2;
        address stack3 = storage3;
        address stack4 = storage4;
        address stack5 = storage5;
        address stack6 = storage6;
        address stack7 = storage7;
        address stack8 = storage8;
        address stack9 = storage9;
        address stack10 = storage10;
        address stack11 = storage11;
        address stack12 = storage12;
        address stack13 = storage13;
        address stack14 = storage14;
        address stack15 = storage15;
        address stack16 = storage16;

        stack1 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack2 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack3 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack4 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack5 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack6 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack7 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack8 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack9 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack10 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack11 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack12 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack13 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack14 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack15 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
        stack16 = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
    }
}
